#!/bin/bash
# vim: syntax=sh

source tools2install/*

mkdir -p ~/bin #you can add this to your PATH
#comment out thinks you don't want
installGNUScreenWithVerticalSplit
installColordiffFromGithub
installAckGrep
