#!/bin/bash
# vim: syntax=sh
repoPath=$(readlink -f "$0")
repoPath=${repoPath%/*/*}

shopt -s globstar
toolsToInstall=$repoPath/scripts/tools2install/*
for file in $toolsToInstall; do
  [ -f "$file" ] && \
    source "$file"
done

mkdir -p ~/bin #you can add this to your PATH
#comment out things you don't want
#installScreenWithVsplit
installColordiff
#installAckGrep

